AllCops:
  NewCops: disable
  Exclude:
    - ./build/**/*
    - ./mruby/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
 Enabled: false

Metrics/BlockLength:
  Exclude:
    - test/**/*
